### ISSUE TITLE
Merge all package tracking IA's into 1, implement new design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1138]
Currently, we have several Package Tracking IA's, each of which is implemented as their own Perl Package. Really, none of these IA's really need to be on their own and should probably be merged so we can continue to add more carriers to the list.

We should be able to create a single "PackageTracking" Goodie which loads a data file that specifies the name, word triggers and regex pattern for their tracking codes. Using this, the Goodie should be able to create triggers and regexes that map to carriers.

In the case that only one carrier works, we can use the new Icon template to produce a result. If multiple providers are valid, we can use the list template to show the matching providers.

Anyone interested in tackling this?
##### New designs

Icon view:
![trackpackage-logos-v1 1](https://cloud.githubusercontent.com/assets/873785/7708631/f9057d52-fe24-11e4-8574-c2f8f24ea61d.jpg)

(This is meant to demonstrate all the logos -- we'd only show one of these depending on the matched carrier)

List view: 
![trackpackage-list-v1 1x3](https://cloud.githubusercontent.com/assets/873785/7708626/ec084558-fe24-11e4-8612-3de315571d99.jpg)

**Comment by abeyang** [comment]
Here are the assets:

http://cl.ly/3q1y1x3P0f2V

**Comment by mintsoft** [comment]
If no-one else has picked this up in a few days I can take it on

**Comment by dronov** [comment]
I would like to fix this issue. So I will made the PR as fast as I can.

**Comment by mintsoft** [comment]
@dronov Excellent! Any problems, just open a PR and someone'll swing in to lend a hand :+1:

**Comment by Mailkov** [comment]
@abeyang @moollaza the icons on  http://cl.ly/3q1y1x3P0f2V must contain background color because background colors of logos are different  IMHO

**Comment by abeyang** [comment]
@Mailkov not sure I understand what you mean. The background color in the mockups should be generated from html/css.

**Comment by Mailkov** [comment]
@abeyang  This is the result when I use icons on http://cl.ly/3q1y1x3P0f2V (in this case BRT and DHL)
![answerpackagetracking](https://cloud.githubusercontent.com/assets/10259499/11871297/e27ebb74-a4ce-11e5-9dd3-3cf949d06a72.png)
As you can see the logos haven't the correct background color ... for BRT (bg color should be a shade of Red) an for DHL (bg color should be a shade of Yellow ).I don't want setting bg color by html/css because it's different for many logos and I don't know the exact color shade.
So the icons must contain bg color, IMHO.
I hope it's now more understandable.
