### ISSUE TITLE
Passphrase: Isn't triggering properly

### ISSUE THREAD

**Issue by zystvan** [duckduckgo/zeroclickinfo-goodies#1144]
The passphrase IA isn't triggering properly. It's [supposed to trigger](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/37ee5f2d3a03555e339f3215c063d868d2f09dd8/lib/DDG/Goodie/Passphrase.pm#L19) when a user searches any of the phrases/words listed on line 19, but instead, "random passphrase" is the only search that triggers it. 

IA: https://duck.co/ia/view/passphrase

**Comment by moollaza** [comment]
Looks like [line 32](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Passphrase.pm#L32) is the culprit. It should account for more variations of "random pass phrase".

**Comment by RomainLG** [comment]
I though that [line 19](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Passphrase.pm#L19) was the line that triggers the instant answer.

Isn't line 32 just to set the number of random words that appear to 4 if nothing is specified when calling for "pass phrase" or its variations?

I'm struggling to understand how instant answers are called I think.

Anyone fixing this please explain to me :)

**Comment by moollaza** [comment]
@RomainLG you're correct. Line 19, defines the `triggers` which are the keywords we look for and if they're present fire the IA's `handle` function. That's the only way IA's get triggered. 

Usually there's more logic in the `handle` query that further qualifies the query to make sure it's something we should actually be dealing with.

For example, we have the trigger "pass phrase", which means the query "what is a pass phrase" will trigger this IA.

We obviously don't want to provide a pass phrase for that query, so we need some logic that makes sure the whole query is one of our trigger words, or that the remainder of the query, after removing the trigger, is something that describes the length of a passphrase, meaning someone searched something like "random passphrase 4".

Line 32 was written when the only trigger was "random passphrase". It's checking if the whole query is just "random passphrase" and if **not** it's trying to parse the query to find a number indicating the length.

This logic is clearly flawed, because there are many other triggers listed but all of them fall to the `else` block and then fail.

This IA needs to be rewritten so that when there is no remainder, we default to a 4 word passphrase. If there is a remainder, we need to see if it's a number and if so, use that as the requested passphrase length.

I hope this makes things clear?

**Comment by RomainLG** [comment]
Thanks **a lot**! I've understood and I'll be trying to issue a fix when I've got time.

**Comment by moollaza** [comment]
:+1:
