### ISSUE TITLE
Passphrase: Phrases are repeated

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1285]
1. Successive reloading shows passphrases re-appearing. They should be one-time use.
2. Successive reloading in a different browser shows the same passphrases re-appearing. No data should be identical cross-browser &mdash; each session should be unique.

Query used: https://duckduckgo.com/?q=3%20word%20passphrase&ia=answer

------
IA Page:  http://duck.co/ia/view/passphrase

**Comment by MrChrisW** [comment]
@tagawa Due to the passwords being generated from a [wordlist](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/passphrase/words.txt) server side using the Perl [rand function](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Passphrase.pm#L49) there's a chance the passphrase will be displayed the same in two different sessions - This is because `rand` isn't truly random and there's a limit of words that can be generated. 

Unfortunately I don't believe there's an ~~easy~~ way to implement the above requirements. We could move to using an API endpoint like [random.org](https://www.random.org/) as this can offer better randomness, however we'd still be limited on the word list :cry:

**Comment by mintsoft** [comment]
Alternatively, is it the browser caching it?

**Comment by tagawa** [comment]
Thanks for the comments @MrChrisW & @mintsoft 
I don't think it can be browser caching because there were a couple of phrases that appeared in two separate browser instances (using Firefox & Vivaldi).
If it's non-trivial and probably not worth the effort of a workaround then I'll live with it as is.

**Comment by mintsoft** [comment]
@tagawa @MrChrisW It might be worth just highlighting this to someone staff wise to see if they're aware/agree. cc @jagtalon @moollaza
