### ISSUE TITLE
Regex Cheat Sheet: Source file links in IA page are wrong

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1416]
In the [IA's view page](https://duck.co/ia/view/regex_cheat_sheet) the links to the source files are broken (404). The link should be to the JSON file: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/regex.json

------
IA Page:  http://duck.co/ia/view/regex_cheat_sheet

**Comment by mintsoft** [comment]
@tagawa the source URL (`http://www.cheatography.com/davechild/cheat-sheets/regular-expressions/`) works for me?

**Comment by seisfeld** [comment]
@mintsoft This is a misunderstanding. @tagawa talks about the Back-End Files and Front-End Files section of the https://duck.co/ia/view/regex_cheat_sheet page. All three links give 404. This probably is because the page was created when the Regex Cheat Sheet was a separate one, vs. now its a generic Cheat Sheet just pulling regex.json. This might not be the only page referring outdated cheat sheets... i did not check though.

**Comment by tagawa** [comment]
Thanks @seisfeld. Yes, that's what I meant - I should have been clearer so I just added a link to the IA view page in the description. I haven't looked through all other cheat sheet pages either so there may be others that need updating.

**Comment by seisfeld** [comment]
The head of the snake (in this case) is https://duck.co/ia/view/cheat_sheets which is the controller serving all the Cheat Sheet json files. For example all json files listed there under Front-End files give 404 because they have been moved. Also the list is by far not complete. So i think the core question is: What is the process (of there is any) that updates the https://duck.co/ia/ pages once there are changes on the repo?

**Comment by moollaza** [comment]
@tagawa thanks for pointing this out!

@tagawa @mintsoft @seisfeld it's actually a known issue, that we're planning to fix.

Right now we haven't been re-building the IA Pages (most IA's don't change once they're live) but in the case of these Cheat Sheets, the pages were made a long time ago and more recently, the CheatSheets.pm file/controller has come along and now all of the source files for "cheat sheets" have changed.

**Comment by zekiel** [comment]
fixed!  https://duck.co/ia/view/regex_cheat_sheet
