### ISSUE TITLE
Locally installing duckpan isn't working

### ISSUE THREAD

**Issue by checkaayush** [duckduckgo/zeroclickinfo-goodies#1727]
Platform: Linux Mint Qiana (Based on Ubuntu 14.04)

On running the command `curl http://duckpan.org/install.pl | perl`, I have the following problem, which seems standard according to the error message:

![screenshot from 2015-11-01 03 19 53](https://cloud.githubusercontent.com/assets/4137581/10866087/7de12b4e-8047-11e5-8d45-6e719a07e5e4.png)

But, I have tried installing and activating perlbrew, reloading the shell configuration and re-login, still nothing works while installing duckpan locally. I had to do so because running the command `duckpan server` on Codio and then opening duckpan server leads to request timing out.

**Comment by mintsoft** [comment]
@checkaayush I've just tested this is `Ubuntu 14.04` and on the first run, I see that error. However if I close and reopen the terminal, `~/perl5` is created by my profile (due to the install of `local::lib`) and then a second run of `curl http://duckpan.org/install.pl | perl` proceeds on until it hits dependency issues (which is a totally separate problem). Is this consistent with the behaviour that you're seeing?

**Comment by checkaayush** [comment]
The problem mentioned above persists for me and I don't seem to reach the state you mentioned. If it helps, I have this line: `export MANPATH=$HOME/perl5/man:$MANPATH` in my bashrc file. I need some cues to look for in order to debug this.

**Comment by checkaayush** [comment]
Fixed! Followed the build.log and had to force install a few dependencies using cpanm and --force option.

**Comment by mintsoft** [comment]
@checkaayush good to hear!
