### ISSUE TITLE
Re-implement HTML Enties Cheat Sheet

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1788]
This is a pretty old internal instant answer and it needs to be moved as an open source goodie to match the "modern" look that we have. https://duckduckgo.com/?q=html+entities&t=ffab

**Comment by jagtalon** [comment]
Another option for the look, you could use something similar to https://duckduckgo.com/?q=shruggie+and+friends&t=ffab&ia=shruggie

**Comment by moollaza** [comment]
@jagtalon I think the problem is that this doesn't lend itself well to a cheat sheet because there's multiple columns of data here. We need an easy way to create tables -- we either need a template that allows for tables with headers, or we may benefit from a new cheat sheet template that produces tables

**Comment by jagtalon** [comment]
@moollaza what about something like https://duckduckgo.com/?q=shruggie+and+friends&t=ffsb&ia=shruggie?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
