### ISSUE TITLE
Why beta.duckduckgo.com didnot shows how the goodies looks?

### ISSUE THREAD

**Issue by jophab** [duckduckgo/zeroclickinfo-goodies#1804]
when we look the pull requests deployed to beta ,,the beta.duckduckgo.com just shows the list of IAs on testing and their information. Not how the IA looks

**Comment by moollaza** [comment]
@jophab if you click the tile, it should expand to show more information including an example URL. You can click the URL to perform a search and see the actual IA instead of a picture. I think that's OK for now.

@jdorweiler do we cache the images anywhere? Would it be possible to reference a single IMG in the detail pane that would always load the most recent screenshot? I think it might be overkill?

**Comment by jophab** [comment]
@moollaza Its working now. But when I made this issue i had tried what you said but it didnt showed how the ia looks. Thats why i made this issue. Now its ok.. :+1:
