### ISSUE TITLE
Atbash: Showing html encoding in answer

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#1887]
For example, with the query `"hello"`;

https://duckduckgo.com/?t=lm&q=atbash+%22hello%22&ia=answer

The formatted query is returning as `Atbash: &quot;hello&quot;`, not pretty!

**Comment by moollaza** [comment]
The reason this happens is because we're escaping the content in the template, for the inputL https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/detail/goodie_1_inputs.handlebars#L5

We need to remove `[html_enc(...)]` from the `input` of Goodies so we can rely on Handlebars to escape any HTML

**Comment by moollaza** [comment]
This should be all the IA's that need fixing: 

- lib/DDG/Goodie/ABC.pm
- lib/DDG/Goodie/Anagram.pm
- lib/DDG/Goodie/Atbash.pm
- lib/DDG/Goodie/Average.pm
- lib/DDG/Goodie/Base64.pm
- lib/DDG/Goodie/Bitsum.pm
- lib/DDG/Goodie/Braille.pm
- lib/DDG/Goodie/Chars.pm
- lib/DDG/Goodie/EmailValidator.pm
- lib/DDG/Goodie/FlipText.pm
- lib/DDG/Goodie/MagicEightBall.pm
- lib/DDG/Goodie/MD4.pm
- lib/DDG/Goodie/MD5.pm
- lib/DDG/Goodie/Morse.pm
- lib/DDG/Goodie/NoteFrequency.pm
- lib/DDG/Goodie/PhoneAlphabet.pm
- lib/DDG/Goodie/PigLatin.pm
- lib/DDG/Goodie/Rc4.pm
- lib/DDG/Goodie/Reverse.pm
- lib/DDG/Goodie/RIPEMD.pm
- lib/DDG/Goodie/Rot13.pm
- lib/DDG/Goodie/Scramble.pm
- lib/DDG/Goodie/Sha.pm
- lib/DDG/Goodie/SHA3.pm
- lib/DDG/Goodie/TimezoneConverter.pm
- lib/DDG/Goodie/TitleCase.pm
- lib/DDG/Goodie/Uppercase.pm
- lib/DDG/Goodie/URLDecode.pm
- lib/DDG/Goodie/URLEncode.pm

**Comment by GuiltyDolphin** [comment]
@moollaza Yeah, I figured it was the `html_enc`, do we have a guide of when exactly things like `html_enc` should be used? And how to make sure we can't get injection attacks (e.g., in the case of `eval`)? 

Presumably the tests will need updating too? As the old input text would need to match the `html_enc` text where applicable.

**Comment by mintsoft** [comment]
@GuiltyDolphin I think with the templating we'd be moving to a situation where outputting of markup isn't possible from Goodies. So they should never be `html_enc`'d. At least I can't think of a situation in which it's required to output encoded html

**Comment by moollaza** [comment]
@mintsoft is correct -- once we really only need to worry about escaping html for old goodies that don't use templates (few remain), or goodies that use the simple structured answer (i.e. input, output, operation).

Moving forward Goodies should be using the full templates which don't need any escaping, because the Goodie shouldn't be creating any HTML, just passing data to templates.

**Comment by GuiltyDolphin** [comment]
@moollaza @mintsoft Could you point me in the direction of some of these full templates? There seems to be a lot of inconsistency with what types of `structured_answer` are used.

**Comment by moollaza** [comment]
@GuiltyDolphin sorry for the late reply, the full templates are all in the docs:

http://docs.duckduckhack.com/frontend-reference/templates-reference.html

You should ideally use template by specifying your template group, `text`, `medai`, `info`, etc. and let the platform take care of choosing the tile and detail templates from chose group.
