### ISSUE TITLE
GUID: Experiencing very similar UUIDs being generated

### ISSUE THREAD

**Issue by aleksen** [duckduckgo/zeroclickinfo-goodies#2002]
@loganom 

Here's a list of some UUIDs being generated:
7D99B174-B2EC-11E5-B3F9-ACCD19563991
8398D366-B2EC-11E5-9070-ACCD19563991
87255784-B2EC-11E5-B102-ACCD19563991
CFB98150-B2EC-11E5-B92C-ACCD19563991
D4408D22-B2EC-11E5-8B30-ACCD19563991

They were created by searching for "uuid"

------
IA Page:  http://duck.co/ia/view/guid

**Comment by moollaza** [comment]
@aleksen it seems that this is acceptable because this is a "Version 1" generator, rather than a "Version 4" which is based on completely random numbers.

I did a quick search and found https://www.uuidgenerator.net/

Looking at it's results, they're similar:
![online_uuid_generator_tool](https://cloud.githubusercontent.com/assets/873785/12093553/9e93f5f8-b2d1-11e5-968b-598338b1c178.png)

**Comment by aleksen** [comment]
V4 uuid would be nice to have :-) But if the intention is to have v1, I'm okay with that

**Comment by ethus3h** [comment]
The instant answer caption describes it as a "Random GUID". I think that would generally be understood to mean it's v4, but it's not. Either the caption or the result should be changed, I think! Thanks!

**Comment by gregmuellegger** [comment]
The problem with V1 uuid is that they might be predictable as time moves linearly forward, so it's expected to yield similiar IDs.

I think as well that UUID V4 would be a better fit here.

**Comment by mintsoft** [comment]
I think my preference would be to generate V4's by default; but the the user specify "10 random type 1 uuids" or

**Comment by moollaza** [comment]
Sounds like we have consensus :+1: 

Anyone want to update this IA?

**Comment by gaulrobe** [comment]
@moollaza I'd like to take a shot at this one!

**Comment by gaulrobe** [comment]
PR submitted!

**Comment by aleksen** [comment]
@gaulrobe Great job!
