### ISSUE TITLE
FedEx: Convert Goodie to Spice and use API

### ISSUE THREAD

**Issue by tjhorner** [duckduckgo/zeroclickinfo-goodies#2046]
FedEx has an API used to track packages and would be a really good implementation on DuckDuckGo to see the last activity of your package for instance.

I could totally help make this a thing if needed (after I finish up my current IA... :sweat_smile:).

Now this isn't an advertised API, it's used for the tracking page.

![image](https://cloud.githubusercontent.com/assets/2646487/12283831/5513db8e-b95f-11e5-8f4e-1d35ee4c5f2f.png)

Results should be cached for a couple of hours.

I can also make an issue over at [zeroclickinfo-spice](https://github.com/duckduckgo/zeroclickinfo-spice) if needed.

Here's how it works:

## Request

`POST https://www.fedex.com/trackingCal/track`

### Headers

| Header         | Value                               |
|----------------|-------------------------------------|
| `Content-Type` | `application/x-www-form-urlencoded` |

#### `data` field

Always JSON data:

```json
{
  "TrackPackagesRequest": {
    "appType": "WTRK",
    "uniqueKey": "",
    "processingParameters": {},
    "trackingInfoList": [
      {
        "trackNumberInfo": {
          "trackingNumber": "[tracking number]",
          "trackingQualifier": "",
          "trackingCarrier": ""
        }
      }
    ]
  }
}
```

#### `locale` field

The locale in the form of "[lang]_[COUNTRYCODE]" (e.g. `en_US`)

#### `version` field

Always `1`.

#### `format` field

Can be one of `json`/`xml`.

#### `action` field

Always `trackpackages`.

## Response

Will return JSON data: [Gist because it's really long](https://gist.github.com/tjhorner/8bd26e002d34d92576c3)

The most useful field here is the `scanEventList` in `packageList` elements.

-------
https://duck.co/ia/view/fed_ex

**Comment by MrChrisW** [comment]
@tjhorner This is a great idea! Having the ability to view the shipment progress directly on DuckDuckGo would be sweet! 

I'm a little unsure about using an undocumented API, only because it could be changed, blocked at any time it could also violate FedEx T&C - I'd like to check that out first. 

CC// @moollaza @jagtalon

**Comment by tjhorner** [comment]
>I'm a little unsure about using an undocumented API... only because it could be changed or blocked at any time it could also violate FedEx T&C

That was one of my first thoughts as well, I tried using [this](http://www.fedex.com/us/developer/) initially but I can't sign in because I'm not receiving the verification email...

**Comment by moollaza** [comment]
@tjhorner @MrChrisW thanks a lot guys! Using a Spice for tracking a package is something I've wanted for a long time. And its funny that you brought this up now, because I've actually been speaking to the co-founder of https://www.packagetrackr.com/ for the past couple days, and they're going to be building an API for us, so we can handle all package tracking searches through a single Spice :smile:

**Comment by moollaza** [comment]
@Mailkov was working on merging the Package Tracking Goodies together so I was going to offer him the opportunity to build this Spice.

**Comment by tjhorner** [comment]
Awesome! I'd love to see this implemented.
