### ISSUE TITLE
Calculator: Add support for Currency math

### ISSUE THREAD

**Issue by askhubchandani** [duckduckgo/zeroclickinfo-goodies#2105]
The calculator calculates the final price of goods if the input is given in $ but not if the input is given in other currencies. It should calculate the numbers and then add the symbol of the input currency.

---

IA Page: https://duck.co/ia/view/calculator

**Comment by GuiltyDolphin** [comment]
@askhubchandani Thanks for the suggestion!

For the near future the Calculator will only support dollars - but after #1927 is sorted I'm planning on implemented a few additional features - including multiple currencies.

**Comment by mintsoft** [comment]
@GuiltyDolphin I've assigned you to this for now, if you can't look at it or anything feel free to remove yourself etc

**Comment by askhubchandani** [comment]
@GuiltyDolphin  Can I build it if you do not have time to develop it?

**Comment by GuiltyDolphin** [comment]
@askhubchandani Sure! You're more than welcome.

I just want to clear up a few things with the way in which currencies are parsed and then you can add them to your hearts content.

Should be a relatively small PR, I'll additionally add a bit of documentation to make it clear what goes where when extending.

**Comment by GuiltyDolphin** [comment]
@askhubchandani I'm not sure these changes would be appropriate in the calculator. After some discussion, it would likely be more useful to have these in a dedicated currency Goodie (https://duck.co/ia/view/currency maybe?) that could *potentially* use some of the calculator's back-end for calculations.

**Comment by askhubchandani** [comment]
@GuiltyDolphin How will these changes not be appropriate? The currency Goodie is for conversions. It does not perform complete calculations. My intention was that the calculator should be able to add/subtract prices of goods in others currencies(one currency at a time) and give the result to the user and not conversions of different currencies.

**Comment by GuiltyDolphin** [comment]
@askhubchandani Sorry, yes - that was just an example; we have other currency IAs that may be more appropriate for this use.

One focus for the calculator currently is support for an interactive front-end, rather than extend the back-end functionality further.

An issue that arises with this (and other calculations involving units) is handling them in conjunction with other units (or unitless values), which is something we may wish to consider further in the future.

If we were able to create another Goodie for these calculations, and use the calculator back-end for more 'advanced' calculations, it would allow us to have a more dedicated design that could highlight important information about the currencies (especially when adding different currencies together).

My feeling is still that this should be handled in a separate Instant Answer that could (possibly) interface with the Calculaor's back-end, but I agree it would be possible to add this to the calculator - I'll open this up to more discussion.

**Comment by moollaza** [comment]
Something of this nature could probably be added to the new JS calculator using a library like http://openexchangerates.github.io/accounting.js/

**Comment by pjhampton** [comment]
[This is now handled at a superficial level](https://duckduckgo.com/?q=%2455+%2B+1234.89&atb=v1&ia=calculator). There just isn't the queries to support currency/accounting math at the moment.
