### ISSUE TITLE
Solar System: Convert to JS Goodie; Pass data from Perl -> JS and check settings for display units

### ISSUE THREAD

**Issue by AndrewSDFoster** [duckduckgo/zeroclickinfo-goodies#2116]
Will not give results in metric, even if metric is selected as the preferred unit in DuckDuckGo

---

IA Page:  http://duck.co/ia/view/solar_system

**Comment by pinusc** [comment]
The example query "mass of earth" works for me.

**Comment by moollaza** [comment]
@AndrewSDFoster thanks a lot for the feedback!

Due to the way this IA is implemented (Perl) it isn't aware of your browser preferences. 

If we convert this IA to use templates and have the Perl pass the data to the frontend, we can enable it to check user preferences and update the results accordingly.

/cc @MrChrisW

**Comment by MrChrisW** [comment]
@moollaza What's the exposed JS prop that provides the users unit setting ?

**Comment by moollaza** [comment]
@MrChrisW `DDG.settings.get('kaj')`

Example usage can be seen here: https://github.com/duckduckgo/zeroclickinfo-spice/blob/65614892002a7770e9d8af4b4dc1234bd367bc32/share/spice/forecast/forecast.js#L336

**Comment by mintsoft** [comment]
@moollaza wtf is a `kaj` !?

**Comment by MrChrisW** [comment]
`DDG.settings` should be documented.... :laughing:

**Comment by moollaza** [comment]
> @moollaza wtf is a kaj !?

@mintsoft Hehehe. We have a "naming scheme" for the URL params and because all settings are also params that's how we look them up. I agree it's weird an non-intuitive to outsiders.

> >@mintsoft hahaha, DDG.settings should be documented.... :laughing:

@MrChrisW `DDG.settings` is really intended for internal (non-DDH) use, but I think we should probably document parts of it (and maybe have more readable aliases for the parameter names :)

**Comment by MrChrisW** [comment]
@moollaza :+1:

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
