### ISSUE TITLE
Calculator: Octal notation?

### ISSUE THREAD

**Issue by jeremykohn** [duckduckgo/zeroclickinfo-goodies#2654]
In DuckDuckGo's calculator, numbers with a prepended `0` are interpreted as octal. This is normal in some programming languages, but it will probably confuse most DDG users.

`10 + 20 // Decimal. Ten plus twenty.`
`010 + 020 // Octal. Eight plus sixteen.`

Is this a bug or a feature?

Related issue: #1880 Calculator: re-write

---

IA Page: https://duck.co/ia/view/calculator

**Comment by GuiltyDolphin** [comment]
@jeremykohn I don't think this was an *intentional* feature. In the re-write you've referenced this is no longer the case; there is no support for bases other than denary at the moment.

If we get a large amount of people requesting support for additional bases then it is something we can look to implementing in the future in a way that doesn't cause any confusion.

**Comment by nunukhalay** [comment]
#3199 Calculato:2654

**Comment by pjhampton** [comment]
Closing this for 2 reasons:

1. We can't support with the math.js front-end
2. From the query data, people just aren't searching for this
