### ISSUE TITLE
HelpLine: additional triggers 

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-goodies#2658]
We received a suggestion that HelpLine could use some additional triggers like 'how to kill myself'. Maybe there is a list of triggers on other search engines that we could use to help expand our trigger list.

@conorfl @hemanth 

------
IA Page:  http://duck.co/ia/view/help_line

**Comment by GuiltyDolphin** [comment]
@yegg There was a PR for this previously: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1563

Unfortunately the original author did not have the time to continue with it - but it should serve as a good starting point.

**Comment by yegg** [comment]
@GuiltyDolphin thank you for the background! Yes, I agree with the Low-Hanging Fruit distinction.

**Comment by pecey** [comment]
Can I take this up?

**Comment by GuiltyDolphin** [comment]
@pecey I don't see why not!

**Comment by yegg** [comment]
@pecey thanks so much!

**Comment by hemanth** [comment]
:+1:

**Comment by pjhampton** [comment]
This is a really super great tool! I think gazetteer approaches like this aren't that affective though. I know machine learning is probably out of the question right now, but what about enhancing this with fuzzy string matching? Implementing something like [Jaro Distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) and triggering it on this list of phrases with a confidence interval of `> 77%` on this list could be beneficial.

For example, 

> ways to kill myslf

or 

> kill myself - ways to

should still trigger the IA.

```
# pjhampton at localhost.local in ~/Desktop [14:24:31]
~~> iex
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.1) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> String.jaro_distance "ways to kill myself", "ways to kill myslf"
0.9824561403508771

iex(2)>
nil

iex(3)> String.jaro_distance "ways to kill myself", "kill myself ways to"
0.7707602339181286
```

Currently it is just including results for:

![screen shot 2016-03-24 at 14 51 04](https://cloud.githubusercontent.com/assets/8960296/14020636/eb434970-f1cf-11e5-878c-e6b0c3107169.png)


thoughts?

**Comment by GuiltyDolphin** [comment]
@pjhampton I agree that this probably isn't the *best* method for *detecting queries*, but I think it will be satisfactory for our uses. There is an upside to this approach which I am rather interested in - if we build a large file of phrases then there would be a easy-to-access, freely available list that *other* people can use in their own projects. Having done some research into this and found it quite difficult to find any reasonable lists, I think this would be hugely beneficial.

Of course, there may well be room to supplement this approach with these algorithms, but we still need the initial phrases otherwise we'd need to trigger on everything!

Have you tried implementing any of these algorithms in Perl?

**Comment by pjhampton** [comment]
@GuiltyDolphin totally understand. I suck at Perl hence the discussion I started on slack yesterday. I am finding myself using it more and more daily and is one of the things that attracted me to DuckDuckHack. We'll move this onto slack.
