### ISSUE TITLE
Calculator modulo operation

### ISSUE THREAD

**Issue by wheatdog** [duckduckgo/zeroclickinfo-goodies#2850]
https://duckduckgo.com/?q=(10%5E100)+%25+10&ia=answer

(10^100) % 10 should be 0. 
I am not sure why the answer is wrong. Is the symbol % represent the modulo operation?

**Comment by GuiltyDolphin** [comment]
@wheatdog Hehe, I imagine it has something to do with the way it handles large numbers :wink:

You'll be pleased to know that on the re-write (#1927) this issue is fixed:

![screenshot from 2016-04-09 10 19 53](https://cloud.githubusercontent.com/assets/8598426/14402966/afc83120-fe3c-11e5-84df-0441e8f0558f.png)

It doesn't support `%` notation atm, though it would be fairly trivial to add in - I'm not sure if it has meaning outside of programming (apart from percent), so I am unfortunately biased.

@duckduckgo/duckduckhack-contributors Anyone know of any other uses? Even if we don't support the infix-operator form, we will always have the function :smile:

**Comment by philipmiesbauer** [comment]
Modulo is a quite common function in maths as well. There is 3 main
notations I have come across.

mod(a; b)
a mod b
a % b

I think all of them would be nice to add to the calculator.

**Comment by GuiltyDolphin** [comment]
@philipmiesbauer Thanks for chiming in!

I think the first and third forms are fine, easily doable; the second would work (treating it as an operator) but I'm not sure how well it would play with *other* infix 'functions' (though it should be fine - we use a full grammar). Updates will be on #2848 - so keep an eye out there :dolphin:

**Comment by wheatdog** [comment]
@GuiltyDolphin Great to hear that! Where can I use the re-write version of calculator? or it is not public right now.

**Comment by mintsoft** [comment]
@wheatdog it's not in a directly accessible location currently; however we hope it get it merged pretty soon!

**Comment by mintsoft** [comment]
@GuiltyDolphin @wheatdog I'm closing this because it's not likely that we'd not merge the rewrite now :)

**Comment by fzzr-** [comment]
Oh crazy world!

* [calculator.pro](http://calculator.pro) ![screen shot 2016-04-11 at 19 44 27](https://cloud.githubusercontent.com/assets/888526/14434979/b4fada62-0026-11e6-920d-58325194fabd.png)
* SwiftCalc.app ![screen shot 2016-04-11 at 19 44 04](https://cloud.githubusercontent.com/assets/888526/14435015/d646354a-0026-11e6-9751-3efabe9e1b13.png)
* [Yahoo](https://search.yahoo.com/search?p=(10%5E100)%20%25%2010) ![screen shot 2016-04-11 at 19 44 38](https://cloud.githubusercontent.com/assets/888526/14434959/95212160-0026-11e6-8d00-6dfe63586c4e.png)
* Google & Bing can't solve it;

**Comment by GuiltyDolphin** [comment]
@wheatdog @fzzr- @mintsoft @philipmiesbauer Okay, drum roll... Here's the super complicated code to add the `%` and `mod` forms (:wink:):

![screenshot from 2016-04-11 18 37 13](https://cloud.githubusercontent.com/assets/8598426/14436414/7c6c5b1a-0014-11e6-94e8-4f693b381d53.png)

And now you can do:

![screenshot from 2016-04-11 18 44 26](https://cloud.githubusercontent.com/assets/8598426/14436630/84411c30-0015-11e6-8910-aaf10b5838e5.png)

and

![screenshot from 2016-04-11 18 44 56](https://cloud.githubusercontent.com/assets/8598426/14436636/8a294dac-0015-11e6-96ae-44b10b3956d1.png)

Enjoy!
