### ISSUE TITLE
Calculator: exponential not always triggered

### ISSUE THREAD

**Issue by mnp** [duckduckgo/zeroclickinfo-goodies#2879]
- `1 * 1e1` triggers correctly into calculator and evaluates to 10.
- `1 * 1.0e1` does not trigger calculator.  For some reason, tabs for Steve Miller's Joker are the first search hit :-)

Test cases should probably include
- all combinations of sign and no sign on exponent and mantissa 
- all combinations of float and int exponent and mantissa 
## Thanks.

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@mnp Thanks for pointing this out - it appears to be fixed in #1927, see:

![screenshot from 2016-04-13 15 18 30](https://cloud.githubusercontent.com/assets/8598426/14496433/112ca814-018b-11e6-8dea-38e55a74f0e3.png)

and

![screenshot from 2016-04-13 15 18 49](https://cloud.githubusercontent.com/assets/8598426/14496742/150cc5d0-018c-11e6-8cb1-4187929523a5.png)

Which should hopefully be merged soon!

**Comment by lnalex** [comment]
@GuiltyDolphin : Not for my part (beta/non-beta)

![capture d ecran_2016-05-12_14-38-15](https://cloud.githubusercontent.com/assets/1835726/15214775/4df5c2b4-184f-11e6-841d-045cd7524307.png)

**Comment by GuiltyDolphin** [comment]
@lnalex I don't believe the Calculator is on beta right now. You can try the changes out locally by checking out the branch on #1927 (let me know if it works).

**Comment by lnalex** [comment]
@GuiltyDolphin Fixed with #1927 :+1:

**Comment by pjhampton** [comment]
Seems solved to me 👍  closing...
