### ISSUE TITLE
Convert Latitude/Longitude: Feedback from user

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2920]
A user on DDG complained about the format of the Instant Answer.  After converting and returning the correct answer, the lat/long is displayed with a "dash" (−) in front of it, instead of a hyphen (-).  Most mapping services use hyphens in this case, so copying and pasting the returned answer doesn't fit the format for most other mapping sites.

------
IA Page:  http://duck.co/ia/view/convert_lat_lon 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wilkox

**Comment by wilkox** [comment]
Currently, negative lat/lon is indicated with a Unicode minus sign (−, U+2212) rather than a dash or a hyphen. To me this seems like the typographically correct way to display a negative value, but I can understand it would be annoying if it doesn't work for copy-pasting. I've opened a pull request #2926 with this change.
