### ISSUE TITLE
Fibonacci: Use perl package for generating sequence

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3068]
Instead of rolling our own, we could use a package like [Math::NumSeq::Fibonacci](https://metacpan.org/pod/Math::NumSeq::Fibonacci) to generate the Fibonacci numbers.

------
IA Page:  http://duck.co/ia/view/fibonacci 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by koosha--** [comment]
The current code is working fine and concise and I don't see any point in this switch.

**Comment by mintsoft** [comment]
@GuiltyDolphin Is there any specific benefit to switching? (Performance perhaps?)

**Comment by GuiltyDolphin** [comment]
@mintsoft The package is faster, has more features (if we wish to expand) and more robust; is it not one of the Perl sayings "Don't re-invent the wheel"?

Anyway, some cool things this package provides:

* `ith` - the `ith` Fibonacci number (can do very large numbers *very* quickly).

* `pred` - check if a number is in the Fibonacci sequence `is 71 a fibonacci number`

Also there's a bunch of other sequences in `Math::NumSeq` so if this were a dependency it would open those up to others.

**Comment by mintsoft** [comment]
Well that's cool; if we want to extend the functionality of the IA then I agree it makes sense to switch it out at that time

**Comment by koosha--** [comment]
Unless you have a concrete utilization of its "more features" for extending, I would still not see any particular point in switching and yet having the same functionality as we do now. In other words, the switch should be made only if you have added a new feature to the code that comes from the proposed module.

**Comment by GuiltyDolphin** [comment]
@koosha-- I quite like the idea of being able to ask `is X a fibonacci number` - I'll make an issue for it.

**Comment by shellhead** [comment]
I was going to start with this story before adding the functionality in #3070 and had a couple of questions.

1. Based on the context, it seems like the current implementation limits requests to 1470 because of precision. Should we still impose the limit or should I play around with it until performance starts to degrade?

2. I noticed its using `remainder`, rather than `remainder_lc`. Thus, "What is the 5th Fibonacci?" doesn't trigger, where "what is the 5th fibonacci" does. Is that desired? Also, for my own information, it seems like both "Fibonacci" and "fibonacci" trigger, assuming triggers are not case sensitive?

Thanks!

**Comment by GuiltyDolphin** [comment]
@shellhead Thanks.

Yeah, generally we want case-insensitive triggering (unless there is a good reason for it :) ).

Yah, the Fib package is a lot faster so you wont notice much difference until really high queries - I'd imagine a *sensible* limit would be fine.
