### ISSUE TITLE
Base Conversion: Query "48 in hex" does not work

### ISSUE THREAD

**Issue by bsinger98** [duckduckgo/zeroclickinfo-goodies#3081]
All other numbers but 48 seem to work correctly.   

---

IA Page:  http://duck.co/ia/view/base 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moritz

**Comment by mintsoft** [comment]
@bsinger98 Are you finding that the product search results for hex screwdrivers are taking precedence? If so there should be an answer tab which contains the actual answer?

**Comment by moritz** [comment]
I don't think the hex plugin fails to convert the value 48, it just that if 48 appears in the search, some other mechanism seems to prefer results from amazon. In fact, the search `48 hex` (without the `in`) works for me.

**Comment by mintsoft** [comment]
@moritz That's the behaviour that I've witnessed too; I believe adding `signal => 'high'` into the returned `structured_answer` should make it take precedence. @moollaza Is this true with the amazon product results or just other IAs?

**Comment by GuiltyDolphin** [comment]
@mintsoft @moritz It's working fine for me https://duckduckgo.com/?q=48+hex&ia=answer

Have you got a region set?

**Comment by mintsoft** [comment]
@GuiltyDolphin Works fine for me now

**Comment by bsinger98** [comment]
@GuiltyDolphin @mintsoft Remember, it only occurs when you search "48 in hex". It works fine when the query is "48 hex" as shown in the link @GuiltyDolphin posted. Here is an example: https://duckduckgo.com/?q=48+in+hex&atb=v12&ia=products.

**Comment by mintsoft** [comment]
@bsinger98 It works for me at the moment with the query "48 in hex"; I'm not seeing the amazon results I saw previously

**Comment by GuiltyDolphin** [comment]
@mintsoft @bsinger98 `48 in hex` triggers both Products and Base with no region set, but only Base when UK region is set.

It seems odd that products would trigger at all if there is no region - seeing as it is a region-specific result; @moollaza does it default to an American region or something?

**Comment by edgesince84** [comment]
@bsinger98 are you not getting an "Answer" tab to the left of "Products" too?  Your example query displayed Products first, but there's an Answer tab as well, for me.

**Comment by moollaza** [comment]
> It seems odd that products would trigger at all if there is no region - seeing as it is a region-specific result; @moollaza does it default to an American region or something?

Yes it defaults to US. FWIW a lot of searches are made without a region. I personally use the Canada region pretty infrequently. I do flip it on though when I need Canadian Amazon results.

It seems like 48 is a popular number across "hex" related products on Amazon. The Goodie does trigger though and work.

> I believe adding signal => 'high' into the returned structured_answer should make it take precedence. @moollaza Is this true with the amazon product results or just other IAs?

@mintsoft I've learned from the Search team that we need to be more careful about the use of `signal => "high"` if multiple IA's have a high signal it can create problems, so really we should be using the appropriate triggering blocks internally as a first solution. In this case we can probably bump the Hex IA into the higher priority class. I don't know if this will guarantee the products IA won't beat it though. It typically has a high signal when it triggers because of the organic results.

**Comment by mintsoft** [comment]
@moollaza Is there an argument that a goodie should always 'win' relative to any other form of IA? Given that they're targeted to very specific queries?

**Comment by GuiltyDolphin** [comment]
@moollaza Why do we default to US? Doesn't that mean we are going to be showing a *lot* of irrelevant results? Even to a point where it is *blocking* the more specific answer (as @mintsoft mentioned); shouldn't 'No Region' *actually* be 'No Region', rather than US? This behavior seems a bit odd to me.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
