### ISSUE TITLE
Nodejs Cheat Sheet: Doesn't trigger for Node.js 

### ISSUE THREAD

**Issue by vikas-bansal** [duckduckgo/zeroclickinfo-goodies#3116]
IA gets triggered for "Nodejs cheatsheet" but not for "Node.js cheatsheet"
------
IA Page:  http://duck.co/ia/view/nodejs_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stanly-johnson

**Comment by edgesince84** [comment]
Hi Vikas, thanks for opening this issue!  "node.js cheetsheat" should definitely trigger this.  Thanks for your input and welcome to DuckDuckHack!

**Comment by vikas-bansal** [comment]
Hey man , thanks for the welcome.

**Comment by edgesince84** [comment]
@moollaza @tagawa was this issue fixed by #3118?  Can we close this out?

Thanks again @vikas-bansal.  If you're interested in working on something, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by stanly-johnson** [comment]
:+1:  
Guess I'm a little late :)

**Comment by tagawa** [comment]
@stanly-johnson No problem - thanks for the thumbs up!

@edgesince84 Yes, this works for the extra triggers now: https://duckduckgo.com?q=node.js+cheatsheet&ia=cheatsheet Thanks @vikas-bansal and @NaveenKarippai for reporting and fixing.
