### ISSUE TITLE
AptGet Cheat Sheet: 

### ISSUE THREAD

**Issue by shahbaz17** [duckduckgo/zeroclickinfo-goodies#3316]
Can't we write in the description to use sudo for certain debian platforms.
Eg.
 If you are getting this error Unable to lock the administration directory , are you root?
      Then add sudo in prefix to all the listed commands.
    OR
Note : All these commands except the search commands must be run as root or with superuser privileges.
 

------
IA Page:  http://duck.co/ia/view/apt_get_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @abadojack

**Comment by abadojack** [comment]
I prefixed all the commands with sudo. I hope that solves the problem.

**Comment by shahbaz17** [comment]
Hey @abadojack thanks for taking your time to fix this. But prefixing all the commands with sudo will not do the good since not all the debian based OS used explicit sudo. Like in debian OS , we don't have to use sudo, also in kali.
So it would be better to write a Note: on description.

**Comment by abadojack** [comment]
Debian, Kali and other Debian-based distros will require _sudo_ when the user isn't root. Since Ubuntu and Linux Mint are the most popular distros in this category and most of their users ain't root, it makes more sense to prefix all the commands with _sudo_. I will however add a note to the description as you suggested.
