### ISSUE TITLE
Question: Cheat sheet for Facebook / Twitter REST API endpoints

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3419]
Inspired from #3375, can we have similar cheat sheet for Twitter / Facebook Rest API endpoints? It will act as a quick reference for those working on Twitter / Facebook API extensively.

If yes, I will take this up and submit the PR for Twitter and Facebook.

/cc @moollaza @GuiltyDolphin @tagawa

**Comment by moollaza** [comment]
I don't love the idea of CheatSheets for APIs because it seems very fragile and prone to requiring updates. A Spice might be better, if we could get a JSON map of the endpoints.

Also, I imagine the FB and Twitter APIs are going to be very large, I'm worried about how large and easy to navigate the Cheat Sheet will be...

Give it a try with one of them and let's see how it looks.

**Comment by sahildua2305** [comment]
@moollaza I tried and planned a cheat sheet around GitHub Rest API but realized you were right. It's beyond the scope of cheat sheets to include all necessary information about ever-changing APIs. Hence, closing this issue.
