### ISSUE TITLE
Bjcp: 

### ISSUE THREAD

**Issue by gustavohmsilva** [duckduckgo/zeroclickinfo-goodies#3466]
---

IA Page:  http://duck.co/ia/view/bjcp

**Comment by tagawa** [comment]
@gustavohmsilva Thanks for creating this issue and the IA page. I guess you're considering using the BJCP data available here? https://github.com/brewpuppy/bjcp-style-data

Or is there another source you're considering?

**Comment by gustavohmsilva** [comment]
Hi tagawa, this data from github is 10 years obsolete... I was thinking in using the last version approved by the BJCP: http://www.bjcp.org/docs/2015_Guidelines_Beer.pdf
I'm still trying to understand how to put together the info to be reacheable by DuckDuckGo. I'm already helping the search engine in the translation but would really like to help with the zeroclick

**Comment by tagawa** [comment]
@gustavohmsilva Oh, I thought the JSON update was only two years ago (Aug 2014). It's much easier to make an Instant Answer by pulling external JSON data rather than manually entering it.

How about making this as a Spice using the JSON data from the brewpuppy repository first, and then updating the data later (if necessary) by sending a separate pull request to brewpuppy? There's a walkthrough tutorial for a similar Instant Answer here: http://docs.duckduckhack.com/walkthroughs/forum-lookup.html or if you prefer videos, there's a screencast here: https://vimeo.com/146959080

**Comment by marianosimone** [comment]
@gustavohmsilva any progress on this one? I love the idea and I could help you out

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.
