### ISSUE TITLE
Roman: Trigger on 'X in roman numerals' (+ cleanup)

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3484]
This IA should trigger on queries like '72 in roman numerals'.

The back-end and tests could do with a lil' clean up too.

------
IA Page:  http://duck.co/ia/view/roman 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): **NONE**

**Comment by mrshu** [comment]
@GuiltyDolphin ugh, it's been years since I saw this IA.

If there is anyone who would like to take the mintainer's position (and therefore do something with the backend and tests as you noted), I would gladly let them have the honors.

@moollaza sorry for bothering you, what is the process of changing the IAs maintainer these days? I would hate to run the process due to my lack of knowledge =)

**Comment by moollaza** [comment]
> what is the process of changing the IAs maintainer these days? I would hate to run the process due to my lack of knowledge =)

@mrshu we can just remove you as the maintainer for now. I'll ask if anyone is interested in taking it over 👍

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone like to take over the Roman Numerals IA?

It looks like it's in need of a little Perl work currently, but shouldn't be a huge commitment moving forward...

**Comment by hchienjo** [comment]
I am willing to take this up... in case no one else does.

**Comment by tagawa** [comment]
Hi @hchienjo. That's very kind of you - thank you!
I've just assigned this issue to you and set you as the maintainer in the [IA page](https://duck.co/ia/view/roman). If you'd prefer not to be the maintainer, just let me know.
Thanks again.

**Comment by hchienjo** [comment]
@tagawa Thanks! Let me have a look.
