### ISSUE TITLE
Conversions: Trigger mph to kmh conversion

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3877]
These don't trigger unless you change it to "kmph":

**55 mph in kmh**
[https://duckduckgo.com/?q=55%20mph%20in%20kmh&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=55%20mph%20in%20kmh&kp=1&kad=wt_WT&kl=wt-wt)

**661 mph to km/h**
[https://duckduckgo.com/?q=661%20mph%20to%20km%2Fh&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=661%20mph%20to%20km%2Fh&kp=1&kad=wt_WT&kl=wt-wt)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
I'll sort out km/h; but kmh isn't the same thing, that'd be Kilometer-Hours.

**Comment by mintsoft** [comment]
Actually km/h already works?

**Comment by bsstoner** [comment]
Nice, km/h does seem to work now, strange.

Do you think it's fair to say that most people mean kmph though? Or could we use the presence of mph as a hint?

**Comment by mintsoft** [comment]
Given that kph works I'm inclined to say no. I've never seen anyone use "kmh" to mean km/h or kph and both km/h and kph work.

**Comment by LoveIsGrief** [comment]
I could not find any reference to "kmh" as a unit of speed. Not on [wikipedia](https://en.wikipedia.org/wiki/Kilometres_per_hour#Kilometres_per_hour_as_an_abbreviation) nor anywhere else listing SI units of speed.

**Comment by bsstoner** [comment]
It's not a matter of whether it is an "official" measure of speed, people are typing it into a search engine and expecting an answer. Google gives them the answer, we don't. The example above is from a real user.

**Comment by mintsoft** [comment]
> Google gives them the answer, we don't. The example above is from a real user.
Hmm, personally I'd say that Google is wrong here. Google tends to substitute its own judgement in place of the users; possibly the biggest reason I switched to DDG is that it didn't. That is, however, a matter of opinion.

It is probably worth noting that google has actually autocorrected "kmh" to "kph", it doesn't 'think' that kmh is a unit of velocity. We don't currently have a way of applying query autocorrection into an IA; I think that would be a better way to implement it in general, rather than cluttering up IA's with incorrect/misleading information.

**Comment by adityatandon007** [comment]
@mintsoft I support your point. This IA do what it is made for and since I am from Asia generally people here use **kmph** or **km/h** instead of _mph_ to refer speed, they don't use **kph** or **kmh** at all.

**Comment by pjhampton** [comment]
Looks like this problem has been solved. 
Feel free to introduce some additional aliases or add them to the edge cases issue.
