### ISSUE TITLE
Suggestion: Math fundamentals cheatsheet

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3914]
### Description

As suggested by @Owlree in https://github.com/duckduckgo/duckduckgo/issues/176#issuecomment-277138928 :

> It would be a good idea to have high school level mathematics cheat sheet, as they are heavily used by students many students. We could use Mathquill for this.

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by adityatandon007** [comment]
I would like to work on this cheat sheet.

**Comment by adityatandon007** [comment]
@tagawa what about Mathquill, I didn't get it

**Comment by tagawa** [comment]
Hi @adityatandon007 and thank you for offering to take on this. I've not seen [Mathquill](http://mathquill.com/) before but it looks like it might not be appropriate for just a cheat sheat. I suggest you just use a resource that looks reliable, so feel free to choose whatever you prefer.

**Comment by Owlree** [comment]
Embedding MathJax is out of the question—too big. MathQuill, on a second thought, is made for inputting math. We do not need input, as we only want a cheat sheet.

Does anybody have anything against pre rendered SVGs? We get the best of both worlds. Crisp looking equations and small files. Plus we don't have to load any external library. To render the equation to SVG server side, we could use MathJax—take a look at [this gem](https://github.com/kgryte/tex-equation-to-svg). The rendering needs to be done only once, when updating the cheat sheet, not every time the cheat sheet is delivered. I can also lend a hand with this task.

**Comment by adityatandon007** [comment]
@Owlree How should I start with this IA since I only know simple javascript and after going through MathJax documentation, I thought that I can use their cdn library link in my cheat sheet html but since you suggested that embedding MathJax would be too big, I don't know where should I start with. 

I haven't used nodejs before and I have no knowledge about nodejs. As you suggested I read the readme of that node.js library but I don't get that thing at all. What steps should I take. I could definitely use some help. Could you guide me step by step. Should we have a private discussion on slack for this. By this I will learn a lot.

**Comment by Owlree** [comment]
@adityatandon007 Sure. _node.js_ is just JavaScript on the server. Nowadays it is used as a general purpose scripting language. I gave you and example of a node.js library that uses MathJax to transform TeX equations into SVG.

After you install node, run `npm install tex-equation-to-svg` to install the library, then look at [the readme](https://github.com/kgryte/tex-equation-to-svg/blob/master/README.md) to see how it can be used. After you understand how its used, look in the code and see how it uses MathJax to convert from TeX to SVG.

**Comment by adityatandon007** [comment]
@Owlree I get it what you're saying. In either case, this cannot come under cheat sheet. The cheat sheet just have a static json file (key val pairs). So first of all we have to change the label of this issue to spice if we want to use external library of MathJax or change it to Goodie if we just want to use MathQuill. 
Then we can decide which to choose on. One more thing, I want to say if we use MathJax it would be better because it will cover up all the browser and it has more browser/cross platform support. So people who are using old version of their browser for some reasons won't have any complains. More over it is a W3 standard and was developed in the first place for just these kind of math equation issues and it looks beautiful, so we don't have to do CSS thing also and can minimize our code. Also they have cdn link to MathJax library so we don't have to hold anything on our servers and cdn is very fast too. 

I would like to hear your thoughts on this, but if you would like to stick to cheat sheet then perhaps that we can look into that svg solution which you suggested earlier.

**Comment by adityatandon007** [comment]
@tagawa please unassign me and assign @Owlree . He would like to work on this. We had discussed this in slack.
