### ISSUE TITLE
Suggestion: Diceware word generator

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3925]
### Description
Example query: `diceware 21126`

Output: `cloak`

We already have a [passphrase generator](https://duck.co/ia/view/passphrase) which uses the Diceware list, but some users may want to choose each word individually, either using physical dice or our [dice IA](https://duck.co/ia/view/dice).

Reference: [About Diceware and howto](http://world.std.com/~reinhold/diceware.html)

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by adityatandon007** [comment]
@tagawa It looks like a good idea but how are you going to accept the input from the user in the search bar. I mean what we user type in the ddg search bar that will display the corresponding passphrase. There are things that we will need to keep in mind like (are commas allowed, are tabs allowed or any other special character or any unprintable character characters between the numbers allowed). Don't assign me this now because I have lot on my plate. Though I would love to hear your response on this accepting input thing. Though I am impressed with this suggestion, it's a great idea. :bulb: :+1:

**Comment by tagawa** [comment]
Thanks for the comment @adityatandon007. Actually I was thinking of just a number as input (as well as the trigger word `diceware`), and that would correspond to a word in the Diceware word list. The word would be displayed on the screen and the user then repeats that until they have as many words as they want for their passphrase.

We could also have a hint that if they want a passphrase instantly, they could just use the existing passphrase generator, e.g. with queries like [`passphrase 5 words`](https://duckduckgo.com/?q=passphrase+5+words)

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
