### ISSUE TITLE
Local Sunrise/Sunset: Sunset on a specific date

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3980]
**sunset at 7th of march 2017**
[https://duckduckgo.com/?q=sunset%20at%207th%20of%20march%202017](https://duckduckgo.com/?q=sunset%20at%207th%20of%20march%202017)
_Comment: When I type in sunset I get a nice result that at this day the sun will set at a certain time with a nice date-stamp, so I tried to edit this date by typing a specified date, but that yielded no fancy "Answers" result as I expected._

------
IA Page:  http://duck.co/ia/view/sun_info 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by Mailkov** [comment]
@bsstoner 
At this moment Sunset works with mm/dd/yyyy type of date
For example:  https://duckduckgo.com/?q=sunset+03%2F07%2F2017

**Comment by mintsoft** [comment]
@Mailkov @bsstoner Actually it works with anything that the DateRole can parse: 
* https://duckduckgo.com/?q=sunset+7th+march+2017&ia=answer
* https://duckduckgo.com/?q=sunset+2017-03-07&ia=answer
* https://duckduckgo.com/?q=sunset+7+march&ia=answer
* https://duckduckgo.com/?q=sunset+7th+march+2017&ia=answer

There are 2 issues described here:
* DateRole should handle: "7th of march 2017" which it currently doesn't
* Sunrise/Sunset should handle: queries like: `at <Date>` rather than just `<Date>`

**Comment by mintsoft** [comment]
Extension for the role to handle the date: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3982

**Comment by mintsoft** [comment]
The PR will make `sunset 7th of march 2017` work; just needs a tweak to sunrise, post-merge.

**Comment by moollaza** [comment]
The PR by @mintsoft has been merged. Would someone like to update the IA accordingly?

**Comment by nalinbhardwaj** [comment]
@moollaza Done.
