### ISSUE TITLE
Base Conversion: Fix Overtriggering 

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3985]
### Problem

![screen shot 2017-03-07 at 7 06 33 pm](https://cloud.githubusercontent.com/assets/8960296/23673216/468b637a-0369-11e7-9cf5-f671169698ed.png)

The above IA (base) **should not** trigger for this query. This is because of [the handle function on line 34](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/ba2760f03485f32f10de1e85c19b11415cb8528b/lib/DDG/Goodie/Base.pm#L34). 

### Solution
The handle function needs to be replaced with another - one that is more appropriate. You can consult the [documentation further on the available handle functions](https://docs.duckduckhack.com/backend-reference/handle-functions.html). 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/base

**Comment by mintsoft** [comment]
@pjhampton What *is* the expected result for that query?

**Comment by pjhampton** [comment]
@mintsoft it shouldn't trigger this IA.

**Comment by moollaza** [comment]
> @pjhampton What is the expected result for that query?

@mintsoft based on https://answers.yahoo.com/question/index?qid=20091203074128AA2UwNK, I think the user might expect to see `0.0001` as the answer?

Anyway, the issue here is more that Base.pm is incorrectly triggering on that query, because it's using `query_clean` which is a little dangerous, as it means we ignore `.` and `%` in the query, which have significant meaning

**Comment by mintsoft** [comment]
> @mintsoft based on https://answers.yahoo.com/question/index?qid=20091203074128AA2UwNK, I think the user might expect to see 0.0001 as the answer?

Ah! It never even occurred to me that the user was asking for 0.01% expressed as a decimal (i.e. 1 is 100%)

**Comment by adv16** [comment]
Hey guys,

Is anyone working on this? Though at this moment I am unsure about what needs to be done, I would like to try. @mintsoft @pjhampton

**Comment by mintsoft** [comment]
@adv16 Go for it! Basically the `Base` IA shouldn't return a result for this query. For me the first step is to add a test like : `'0.01 % in decimal' => undef,` into the Base.t and then make the test pass 👍

**Comment by adv16** [comment]
Thanks for this inputs @mintsoft @pjhampton .. I could make the newly added test case pass just by changing the handle to query_lc so that it allows non alphanumeric characters and the IA does't trigger anymore..
But I am not fully convinced with this..it feels like a lot of hard coding in the IA.. Also this IA somehow assumes that we are never going to get floating point numbers in the query.. so even after allowing the non-alphanumeric characters it will not even provide results for queries like  "0.2 in decimal".. Any thoughts on what should be done about this?

**Comment by mintsoft** [comment]
@adv16 Can you open a PR for the changes? We'll discuss the solution etc in there

**Comment by adv16** [comment]
PR #4010 opened. Please have a look. Thanks.
