### ISSUE TITLE
Please Document Font Selection

### ISSUE THREAD

**Issue by KO0I** [duckduckgo/zeroclickinfo-goodies#4153]
### Description
When using figlet on duckduckgo.com, the example, default, case is shown. I noticed that duckduckgo.com also *displays* which font I had used. This implied I had options, so following the info and coming here, I had found that you truly had multiple fonts. Great! I love ASCII art.

However, so far, I have not been able to find or figure out how to actually tell duckduckgo.com to use another font (examples: "figlet -f 3d foo", "--font=3d", etc.). Other users might find that same area where the font name is currently being displayed to have a small drop-down where other fonts could be selected. 

Anyway, if there's a way to change the font, I would like to know how.

## Steps to recreate
n/a

---

Instant Answer Page: https://duck.co/ia/view/figlet

**Comment by moollaza** [comment]
@KO0I if you click the little "i" icon beside the result you'll be able to see the Instant Answer page for Figlet: https://duck.co/ia/view/figlet

Here we have some example queries that should demonstrate the triggering.

In this case, you just need to provide the name of the font to use: "figlet <font name> <text>"

We _could_ supply a dropdown, but because this Goodie is implemented in Perl we'd need to force a re-query (like doing another search) to show the updated result. This means we'd also need to provide a button for searching again, or we'd need to listen for changes to the dropdown force a requery after you select another font. I'm not sure how well that will work out, but I suppose we could try it and see.

**Comment by KO0I** [comment]
Oh. What I was trying to do is literally the second example. I can't believe I didn't figure this out. I just went straight to github :S

The text input is actually my preferred way. I am sorry for bothering you!
