### ISSUE TITLE
Conversions: JSON format no longer populated

### ISSUE THREAD

**Issue by sixhobbits** [duckduckgo/zeroclickinfo-goodies#4164]
### Description

Various conversions are no longer accessible in JSON/XML format. Previously one could append `&format=json` to conversion queries sent to DDG and find the answer to the conversion in the `Answer` section of the JSON. Now the JSON largely consists of empty fields. Is this part of https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4159? 

## Steps to recreate
Visit https://duckduckgo.com/?q=1+mile+to+km&ia=answer&format=json

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by pjhampton** [comment]
Hi @sixhobbits, 

We're no longer calculating conversions on the backend and calculating them off the front-end because of the new interactive UI. 

https://duckduckgo.com/?q=unit+converter&t=h_&ia=answer 

This improves the search experience for many of users. Sorry it's no longer supported via the API
