### ISSUE TITLE
Calculator: Add ability to paste values into calculator

### ISSUE THREAD

**Issue by jonathancross** [duckduckgo/zeroclickinfo-goodies#4202]
Would be great if we could paste (Ctrl-v) into the calculator.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Yeah, I like that idea. Will implement next week! 👍

**Comment by pjhampton** [comment]
Assigning @souravbadami based on slack convo 👍

**Comment by pjhampton** [comment]
@souravbadami are you still working on this?

**Comment by pjhampton** [comment]
Ok, I looked into this. The issue with implementing this suggested feature is because:

1. We don't us an HTML `<input />` field, we use a span. So we can't rely on the user's computer, and:
2. Using JS to grab from the users keyboard isn't going to work cross browser, so we can't give the users a consistent experience. See this [Stack Overflow answer](https://stackoverflow.com/questions/6413036/get-current-clipboard-content/6413100#6413100).
3. Not everyone uses `ctl`, some use `cmd` which we can't capture. 

So this is a user/browser support issue.
Never say never, but not for now 👍  sorry to disappoint @jonathancross.

**Comment by jonathancross** [comment]
Yeah, I suppose it would have to be a paste button unless you are interested in switching to an `<input>` element.
