### ISSUE TITLE
Calculator: wrong answer 1.0001 ** 78

### ISSUE THREAD

**Issue by wpk-** [duckduckgo/zeroclickinfo-goodies#4279]
The answer to 1.0001 ** 77 is correct: 1.0077...
But the answer to 1.0001 ** 78 is incorrect: 1
It should be 1.0078...

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by adityatandon007** [comment]
@pjhampton it shows the answer `1` for `1.0001**78` and above exponents like `1.0001**79` and so on.
Similarly, it happens for `1.0002**84` and above 
![screenshot from 2017-06-12 15-54-40](https://user-images.githubusercontent.com/25108385/27029847-aa0bec0c-4f87-11e7-81b9-709daa3f712a.png)
![screenshot from 2017-06-12 15-48-34](https://user-images.githubusercontent.com/25108385/27029855-afd76b2a-4f87-11e7-8c23-90da78948f41.png)

Is it happening because of the memory capacity, not sure though :slightly_smiling_face:

**Comment by mintsoft** [comment]
IMO: it should preserve the number of significant figures in the input

**Comment by adityatandon007** [comment]
@mintsoft I completely agree with u
