### ISSUE TITLE
Calculator: Dividing in firefox steals focus

### ISSUE THREAD

**Issue by JakobBruenker** [duckduckgo/zeroclickinfo-goodies#4284]
Pressing `/` (regular or on numpad) in firefox opens firefox's Quick find search function, I suppose because the calculator doesn't act like an input field. This steals the focus from the calculator and is very annoying. (Perhaps an interesting side note is that the same applies to Google's calculator)

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Turns out Bing's calculator also does this. 
It turns out this is a bug in Firefox and has been for 13 years. To get around this we would have to override some user settings and I'm sure a lot of users appreciate that. We're [between a rock and a hard place](http://www.phrases.org.uk/meanings/between-a-rock-and-a-hard-place.html), and I feel at this present time we're better doing nothing at all
