### ISSUE TITLE
URL Decode: UTF-8 characters are incorrectly decoded

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4475]
### Description
Percent-encoded characters comprising more than one percent sign are decoded by URL Decode as if they were just one character. For example; `%C3%9C` becomes `Ã` but should be `Ü`.

## Steps to recreate

Search for [`%C3%9C`](https://duckduckgo.com/?q=%25C3%259C). This becomes `Ã` but should be `Ü`.
Search for [`%E4%B8%AD%E6%96%87`](https://duckduckgo.com/?q=%25E4%25B8%25AD%25E6%2596%2587). This becomes `ä¸­æ` but should be `中文`.

Tested on Firefox 55.0.3 and Safari 10.1.2, on macOS Sierra 10.12.6.

------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by pjhampton** [comment]
Adding the discussion label until the potential bug is scoped out.

**Comment by jc86035** [comment]
Basically all [this](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/URLDecode.pm) does is `uri_unescape($in)` and return, so it might be an upstream bug?

**Comment by mintsoft** [comment]
It's most likely that the input string isn't being handled as utf8

**Comment by hektr** [comment]
Not only input string, but also output string :)
if  instead of `title => $decoded,` I write this `title => "микрокредит hey"`, then I'll get this output "Ð¼Ð¸ÐºÑÐ¾ÐºÑÐµÐ´Ð¸Ñ hey".  So, it doesn't output utf8 characters.

btw, I've found, how to output correct string, but **I don't know, why it works** :) I'll commit it if you want.
