### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by slremy** [duckduckgo/zeroclickinfo-goodies#4611]
Greetings from Kenya.. This instant answer unfortunately isn't producing the correct result.

[Try it!](https://duckduckgo.com/?q=9am+est&t=hf&ia=answer)
<img width="663" alt="image" src="https://user-images.githubusercontent.com/871503/38743554-0dc605c4-3f48-11e8-880b-905db5dd5548.png">
 
VS

[Timebie](http://www.timebie.com/std/est.php?q=9) which says that it's 4pm EAT.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment]
@slremy When you use EST on Timebie it seems to switch it to EDT, because EDT is in effect right now. You'll see that the Offset adjust to UTC-4

http://www.timebie.com/timezone/esteat.php

Our answer is technically correct, if you change the query to EDT it will show the result you're seeing on Timebie: https://duckduckgo.com/?q=9am+EDT+to+EAT&t=ffab&ia=answer
