### ISSUE TITLE
Conversions: Digital Storage conversion is incorrect for TB:GB

### ISSUE THREAD

**Issue by shannon714** [duckduckgo/zeroclickinfo-goodies#4620]
Thanks for the cool tool.
Unless I'm using it wrong 1 Terabyte = 1024 Gigabytes.  It currently returns 1000.  The GB:TB conversion is also incorrect.
Shannon
------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Heya @shannon714 

This seems issue seems to come up quite a bit. The most recent is https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4610

The reasoning behind this was because other search engines do this and, at the time of development, didn't want to confuse users coming from these search engines. Although I don't work with DDG anymore, I can say with confidence this will probably stay this way in the foreseeable future.

take it easy
