### ISSUE TITLE
Conversions: "3 tablespoons to cups" assumes tablespoons are Imperial and cups are US Legal

### ISSUE THREAD

**Issue by TaylorSMarks** [duckduckgo/zeroclickinfo-goodies#4632]
Like the title  says. The issue is there are 16 (imperial) tablespoons in a (imperial) cup, but that doesn't work out with US Tablespoons or US Legal Cups (also, there are no US Cups or US Legal Tablespoons?)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by Ivan218** [comment]
https://duckduckgo.com/?q=cups+to+tablespoons&t=ffab&atb=v133-6__&ia=answer

Turns out there are currently US cups and US tablespoons. But my issue here is the inconsistent use of imperial vs. US. As this search query yielded for me at the time, 1 US cup is equivalent to 13.5 Imperial tablespoons. Thankfully there is an option to switch units, but the default being inconsistent is not likely to be helpful for anyone.
