### ISSUE TITLE
Calculator: wrong answer to pretty basic multiplication

### ISSUE THREAD

**Issue by lowellk** [duckduckgo/zeroclickinfo-goodies#4645]
47.77 * 80000 is evaluated to 3821600.0000000005 which is not correct   

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by lowellk** [comment]
True, but a calculator that gives wrong answers is a pretty bad calculator. IMO it'd be better to remove the calculator rather than having it be unreliable. This is not an advanced calculation.

**Comment by empjustine** [comment]
*Any* calculator by your definition gives wrong answers, because by definition in any radix, there's numbers that can't be represented correctly without infinite digits and will end up rounded. If the user enters such numbers it will "give wrong answers".

The difference, however, is that in most simple calculators **_you can't notice the answer is wrong_**.

I believe that, as a human being, *noticing the anwser is wrong* and checking _significant figures_ is more important that hiding the fact the result is wrong.
