### ISSUE TITLE
"20% of 100" doesn't work

### ISSUE THREAD

**Issue by karan** [duckduckgo/zeroclickinfo-goodies#4688]
### Description

According to the tips IA, "20 percent of 100" and "20% of 100" should work and have an instant result. But they don't.

## Steps to recreate

https://duckduckgo.com/?q=20+percent+of+100
https://duckduckgo.com/?q=20%25+of+100&ia=web

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/tips

**Comment by Essler** [comment]
It seems [Tips](https://duck.co/ia/view/tips) was never meant to handle this:
```
    # queries that will be handled by the calc
    '25 percent of 20000'             => undef,
    '2% of 25,000'                    => undef,
    '2% of $25,000'                   => undef,
    '2,000% of -2'                    => undef,
    '20% tax on $20'                  => undef,
```

Even Google uses their general calculator rather than their tip calculator:

!['20% of 100' Google search](https://imgur.com/yqMFzhp.png)

But [Calculator](https://duck.co/ia/view/calculator) doesn't currently trigger on "20% of 100" or any variations either, so that may be the real issue.
