### ISSUE TITLE
Help Line: 

### ISSUE THREAD

**Issue by XxX-Force** [duckduckgo/zeroclickinfo-goodies#4700]
Hello. This is regarding the results for the search query "suicide". https://duckduckgo.com/?q=suicide&ia=answer**

![DDG "suicide" search result](https://i.imgur.com/We7a62rr.jpg)

IMO, the "Instant Answer" is nowhere near big enough. Should be at least twice the size and made to stand out more. IMO the user, especially in a state of distress, can just gloss right past it. It should be put front and center in their face.

Somehow, Google just makes it stand out more:
![Google "suicide" results](https://i.imgur.com/0CRgzmFr.jpg)

***
_>"You're not alone. Confidential help is available for free."_
Is a helpful touch as well, and may help a user in distress.
And, as can be seen, Google also includes and encourages instant access to a live chat, which will take the user right here:

![Live Chat](https://i.imgur.com/R1sejvOr.jpg) 

***
Also, I'm sure this is just a problem on my end, but when I click "Show More", nothing happens (besides the text changing to "Show Less":
![Show More](https://i.imgur.com/khBca1or.jpg)

If I click "Show Less", the entire field disappears:
![Show Less](https://i.imgur.com/EBJRpJgr.jpg)

***
I hope I'm submitting this correctly and to the right place. Please forgive me if I've screwed anything up, I'm not a developer and have no idea what I'm doing. But this issue may actually help save someone's life, so I wanted to make my opinion known. Thank you, and thank you all for DuckDuckGo!
***
IA Page:  http://duck.co/ia/view/help_line 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ConorFl 
***
@hemanth
@pecey
@mintsoft 
@NaveenKarippai
@mattr555

**Comment by moollaza** [comment]
@XxX-Force thanks for the feedback.

> IMO, the "Instant Answer" is nowhere near big enough. Should be at least twice the size and made to stand out more. IMO the user, especially in a state of distress, can just gloss right past it. It should be put front and center in their face.

Regarding the size, I think we can increase the font size a bit, but it seems like you're using a custom color scheme which makes the Instant Answers stick out a little less. In our default dark/light themes I think the Instant Answer stands out enough that it won't be glossed over. We don't have immediate plans for all Instant Answers, but we are working towards making them feel more like the results in a similar way to your Google example.

> _>"You're not alone. Confidential help is available for free."_
> Is a helpful touch as well, and may help a user in distress.
> And, as can be seen, Google also includes and encourages instant access to a live chat, which will take the user right here:

I agree, that's a nice touch and could be added. The link to the chat could be added to the list of phone numbers for US users, as it only applies.




> Also, I'm sure this is just a problem on my end, but when I click "Show More", nothing happens (besides the text changing to "Show Less":

Nope this is a bug on our end. It's low priority so I don't think it will be fixed anytime soon because DuckDuckHack is in Maintenance mode so we're trying to keep updates to Instant Answers to a minimum. The bug is part of the show/hide logic for tables, so it's not specific to this Instant Answers.

>  I hope I'm submitting this correctly and to the right place.

You have 👍 

> Please forgive me if I've screwed anything up, I'm not a developer and have no idea what I'm doing.

You haven't. 

>But this issue may actually help save someone's life, so I wanted to make my opinion known. Thank you, and thank you all for DuckDuckGo!

Thanks again for taking the time to share your thoughts 👍

**Comment by PARVEENSINGH** [comment]
Can I take it up? @moollaza Please guide me.
