### ISSUE TITLE
Calculator: Add uniform support for atan, atan2

### ISSUE THREAD

**Issue by kunaltyagi** [duckduckgo/zeroclickinfo-goodies#4709]
### Description
`asin` and `acos` using the calculator widget (and more often than not via simple search) returns the correct results. Can we show the same love to `atan2`? It's a lovely function :smiley: 

## Steps to recreate

* Search for `atan(1)` or `atan2(1, -1)` to get search results but no calculator widget
* Confirm that search isn't broken by using `asin(1)` or `acos(0.707)`

Sometimes after searching for `asin(...)` the calculator widget appears after which it's possible to perform `atan`, though many times, it gets redirected to normal search page. Sadly, atan2 has bumpier support. It can result in a normal search page, or blank calculator.

![Blank calculator](https://user-images.githubusercontent.com/2657068/56557773-503c1680-65d7-11e9-9951-0244a1825a3b.png)

This might be a common bug since the blank calculator also appears on `asin(1) deg`

PS: Is there a reason for the calculator to vanish while searching for `atan`? or `asin(1) in degree`.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment]
> Can we show the same love to `atan2`? It's a lovely function 😃

@kunaltyagi Thanks for the suggestions. Unfortunately, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

> Search for atan(1) or atan2(1, -1) to get search results but no calculator widget

`atan(1)` works for me? 
<img width="932" alt="atan(1)" src="https://user-images.githubusercontent.com/873785/56590563-4e615b80-65b5-11e9-99ad-9e5aa23d7f2f.png">

> Sometimes after searching for `asin(...)` the calculator widget appears after which it's possible to perform `atan`, though many times, it gets redirected to normal search page.

Can you please provide some example links so I can try to recreate this?

> Sadly, atan2 has bumpier support. It can result in a normal search page, or blank calculator.
I don't believe we support the atan2 operator. It looks like a search for `atan2` is interpreted as `atan(2)` which may have been intentional.

The blank calculator means we detected it as a calculation but had an issue parsing the query (unsupported operators) or, if I am remembering correctly, it might also mean the answer wasn't possibly to calculate (bad input)

> PS: Is there a reason for the calculator to vanish while searching for `atan`? or `asin(1) in degree`.
In the case of `atan` there's no input to the function so we don't trigger the calculator. For example a user could be searching to understand what 'atan' is in this case. For `asin(1) in degree`, this is considered an invalid input. The calculator doesn't handle unit conversions, so we don't show anything here.

Unless there's an actual issue with `atan` this will be marked as tolerated and closed.
