### ISSUE TITLE
Markdown Reference: No results shown in website

### ISSUE THREAD

**Issue by mbedded** [duckduckgo/zeroclickinfo-goodies#4758]
Hello together,

i was looking around the existing goodies and found this one. Unfortunately the Browser (Brave, Linux Mint) does not show a result. The examples from the IA Page are not working either.

Screenshots:
![image](https://user-images.githubusercontent.com/22235508/83779083-c987b300-a68b-11ea-927e-a501dc2e498e.png)

![image](https://user-images.githubusercontent.com/22235508/83779028-b83ea680-a68b-11ea-9e64-02cf4af2c2ff.png)

![image](https://user-images.githubusercontent.com/22235508/83779042-bd9bf100-a68b-11ea-82db-6f08b50ea837.png)

------
IA Page:  http://duck.co/ia/view/markdown_reference 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by moollaza** [comment]
@mbedded thanks for reporting. It looks like this IA is offline in production, which is why it's not triggering.

The [Markdown CheatSheet](https://duckduckgo.com/?q=markdown+cheatsheet&t=ffab&ia=answer) is still online and can be used instead.

DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports. Seeing as this isn't critical, the IA will remain offline and I'll mark this as tolerated and close the issue.

**Comment by mbedded** [comment]
Alright, thank you for that information. I didn't saw that DuckDuckHack is in maintenance mode.
