### ISSUE TITLE
UnicodeFuzzySearch: Broken images in some queries

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#926]
https://duckduckgo.com/?q=emoji+poo&ia=answer

**Comment by jagtalon** [comment]
See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/592#issuecomment-70294295

**Comment by moollaza** [comment]
@jagtalon I'm not seeing any broken images?
![2015-01-16_13h14_02](https://cloud.githubusercontent.com/assets/873785/5781545/a18c7c3c-9d81-11e4-9aeb-f6cb389a6c19.png)

Using Firefox 36

**Comment by jagtalon** [comment]
@moollaza ah you're right--it's because it's using the `alt` tag though:

![screen shot 2015-01-16 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/81969/5781585/010bba2e-9d82-11e4-858b-1aa6ce728d8a.png)

The image URL itself, however, doesn't actually work:

![screen shot 2015-01-16 at 1 17 37 pm](https://cloud.githubusercontent.com/assets/81969/5781594/16f7efba-9d82-11e4-8074-e4bbbee95bd0.png)

**Comment by heytitle** [comment]
@jagtalon @moollaza  It seems emoji-cheat-sheet.com uses this file name from `pile of poo` emoji.

**Comment by moollaza** [comment]
> Perhaps we should consider using twemoji instead because it uses hex code for mapping emoji's images.

@heytitle if it'll get things working correctly, I'm all for it! :+1:

**Comment by jagtalon** [comment]
@heytitle @moollaza Here's another one:

![screen shot 2015-01-21 at 11 08 52 am](https://cloud.githubusercontent.com/assets/81969/5843003/4caad296-a177-11e4-9283-c50f0e3fc157.png)

![screen shot 2015-01-21 at 2 10 57 pm](https://cloud.githubusercontent.com/assets/81969/5843013/58ffbfd4-a177-11e4-8c31-3f912870b34d.png)

**Comment by moollaza** [comment]
Closing this issue. For now we've taken this Goodie offline due to the bugs in the output.

After looking into Twitter's Emoji I think we should definitely use their set of images (it covers all 800+ current Emoji). 

Our designers are working on a new design which will hopefully produce a tiled view using the brand new (coming very soon) Goodie Templates.

Once the Goodie templates are available and the design is finished we'll post an issue so someone (perhaps @heytitle?) can implement the new and improved Emoji IA.

@heytitle sorry that we had to take it down so soon after it went live. We (DDG) should have spent more time ensuring the output was consistent and acceptable. I promise the next version of this Goodie is going to be amazing!

**Comment by moollaza** [comment]
Closing this issue. For now we've taken this Goodie offline due to the bugs in the output.

After looking into Twitter's Emoji I think we should definitely use their set of images (it covers all 800+ current Emoji). 

Our designers are working on a new design which will hopefully produce a tiled view using the brand new (coming very soon) Goodie Templates.

Once the Goodie templates are available and the design is finished we'll post an issue so someone (perhaps @heytitle?) can implement the new and improved Emoji IA.

@heytitle sorry that we had to take it down so soon after it went live. We (DDG) should have spent more time ensuring the output was consistent and acceptable. I promise the next version of this Goodie is going to be amazing!

**Comment by heytitle** [comment]
@moollaza  No problem.

I've checked Chrome's bug tracker and it seems that Emoji bug on Chrome has been fixed already and being tested on Chrome's Canary track. So it isn't so far to get the real fix for this issue.

Reference
https://code.google.com/p/chromium/issues/detail?id=62435
http://thenextweb.com/google/2015/01/11/emoji-support-finally-coming-google-chrome-os-x/
